### ISSUE TITLE
support SQL

### ISSUE THREAD

**Issue by SaintDako** [SaintDako/node-email-verification#12]
although MongoDB is definitely web-scale, it would be good to support SQL. I was thinking of using Sequelize to support all of the different kinds of SQL DBs buuuuut I know nothing about ORMs and if this is the place to use one.

cc @frankcash

**Comment by SaintDako** [comment]
running into callback issues with Sequelize (due to Bluebird), so I'm going to write Postgres (`pg`) and MySQL (`node-mysql`) code separately.

**Comment by whitef0x0** [comment]
+1
