### ISSUE TITLE
support Neo4j

### ISSUE THREAD

**Issue by SaintDako** [SaintDako/node-email-verification#29]
support ALL the things

:cake:

**Comment by frankcash** [comment]
Hell ya

**Comment by whitef0x0** [comment]
Does it support Neo4j now @SaintDako?

**Comment by SaintDako** [comment]
@whitef0x0 Nope, but I'm no longer going to be maintaining this. I personally don't care about Neo4j.

**Comment by whitef0x0** [comment]
@SaintDako maintaining this library?

**Comment by whitef0x0** [comment]
Are there any active maintainers right now?

**Comment by SaintDako** [comment]
There are not

**Comment by whitef0x0** [comment]
@SaintDako I have a large popular project which is has this as a dependency. I'd be happy to take over ownership

**Comment by SaintDako** [comment]
Cool, that works for me. Is your project part of a Github organization?

**Comment by whitef0x0** [comment]
@SaintDako I'm about to move it over to one. My github oeg is tellform

**Comment by whitef0x0** [comment]
Some of my project is

**Comment by whitef0x0** [comment]
*github org

**Comment by SaintDako** [comment]
Ok, cool. I'll transfer you the ownership then.

**Comment by SaintDako** [comment]
You'll have to delete your fork from your Github first, it's saying that "whitef0x0/node-email-verifcation already exists".

**Comment by whitef0x0** [comment]
@SaintDako can you also give me publishing access on npm? My npm username is @whitef0x0

**Comment by whitef0x0** [comment]
@SaintDako done
