### ISSUE TITLE
Validation error while creating generated user model

### ISSUE THREAD

**Issue by prakashjais99** [SaintDako/node-email-verification#31]
var userSchema = new mongoose.Schema({
        name: {
            first: {type: String, required: true, trim: true},
            last: {type: String, required: true, trim: true}
        },
        password: {type: String, select: false}
    });

    nev.generateTempUserModel(User)

    var user = new User();
    user.name.first = req.body.name.first;
    user.name.last = req.body.name.last;

nev.createTempUser is throwing below validation error

    ValidationError: temporary_users validation failed for name.first and name.last

Please let me know if this expected or error from my side

**Comment by SarasArya** [comment]
Same is with me. temporary_users validation failed. I thought the schema was not getting generated. But it is getting generated, still throwing this error? Why?

**Comment by SaintDako** [comment]
hey, sorry I haven't worked on this in a while. I will try to get around to it sometime this week!

**Comment by frankcash** [comment]
LET'S HACK IT BRUH

**Comment by SarasArya** [comment]
Hey, guys, it's solved now. If your main schema has some components which in which required is true and while creating a new temporary object you don't declare them, you get an error saying temporary_users validation failed.

**Comment by SeunghunSunmoonLee** [comment]
but if you set persistent user model , then it  automatically takes care of it, right?
