### ISSUE TITLE
nodemailer-mandrill-transport may not be required as a dependancy?

### ISSUE THREAD

**Issue by qualitycode** [SaintDako/node-email-verification#33]
According to bithound, nodemailer-mandrill-transport does not seem to be required.  See  
https://www.bithound.io/github/SaintDako/node-email-verification/master/dependencies/npm

**Comment by whitef0x0** [comment]
Yes you are correct it is not needed

**Comment by whitef0x0** [comment]
@SaintDako this can be closed as its fixed
