### ISSUE TITLE
sendConfirmationEmail not working for me

### ISSUE THREAD

**Issue by MSkaffari** [SaintDako/node-email-verification#34]
I still receive confirmation emails when I configure email-verification with 

sendConfirmationEmail: false

**Comment by whitef0x0** [comment]
I fixed this in my most recent PR.

**Comment by MSkaffari** [comment]
Very cool. this works. 

You might want to fix the documentation also. The docs say

    sendConfirmationEmail: true/false

When the parameter in the code is 

    shouldSendConfirmation: true/false

**Comment by whitef0x0** [comment]
Just updated #36 to change the README for this.
